type users {
    name: String!
    email: String!
    image: String!
}

type chat {
    content: String!
    user:  users! 
    timestamp: String!
}

type sessions {
    sessionToken: String!
    userId:  String!
    expires: String!
}

type Query {
    allMessages: [chat!]
    allUsers: [users!]
    allSessions: [sessions!]
    userIDByEmail(email: String!): String! @resolver(name: "getUserIDByEmail")
}